### ISSUE TITLE
No visual cue after unloading of tabs

### ISSUE THREAD

**Issue by ElDani82** [onemen/TabMixPlus#139]
Hi!

I've been testing the latest pre-7 on the current Firefox Beta and noticed a minor issue when tabs are unloaded.

The extension I use is called [UnloadTabs](https://addons.mozilla.org/en-US/firefox/addon/unload-tabs/), but I also tested with [Tab Unloader](https://addons.mozilla.org/en-US/firefox/addon/tab-unloader-we/).

In both cases, the design of the recently affected tab remains unchanged, although it has been properly unloaded. I noticed that the `tab.tabbrowser-tab` element doesn't gain the `tabmix_tabState="unloaded"` attribute like other unloaded tabs have.

Is that difference between tabs unloaded at browser start and those unloaded during a session intentional? Or is there a way to mark unloaded tabs equally?

The same situation works properly with TreeStyle Tab on the same browser (if custom CSS is used to show unloaded tabs differently).

Thank you and best regards,
Daniel

**Comment by onemen** [comment]
> The same situation works properly with TreeStyle Tab on the same browser (if custom CSS is used to show unloaded tabs differently).

can you post the custom CSS you are using with TreeStyle ?

**Comment by ElDani82** [comment]
Sure!

````css
/* Change visuals of unloaded/hibernated tabs */
.tab.discarded {
	opacity: 0.80 !important; /* was 0.65 */
	filter: grayscale(85%) !important; /* was grayscale(50%) */
}
.tab.discarded:hover {
	opacity: 1.00 !important;
	background-color: #A0A0A0 !important;
}
.tab.discarded tab-item-substance {
    background-color: black !important;
}
````

I haven't looked at the inner workings of TreeStyle Tab, but the Firefox extension API provides a tabs.onUpdated [event listener](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/Tabs/onUpdated), that can fire whenever a tab is discarded.
