### ISSUE TITLE
Hidden color on top row when using Nulti-Account Containers

### ISSUE THREAD

**Issue by legandro** [onemen/TabMixPlus#140]
I've been using css for multi-row tabs + other add-ons for other things and I'm really happy to see there's a way to use TabMixPlus again!

I use "multi-account containers" in conjunction with "Simple tab groups" extension.
Every container has it's own color witch is shown with a color line on the top of the Tab.
Using TMP made that color line disappear on the top row (the other rows show it fine). 
If I'm on one of the top row tabs, then a thin line is shown, and at the same time the tab gets over the color line from the tabs bellow.
I'm attaching a screen grab showing this issue.
![TMP](https://user-images.githubusercontent.com/39671907/167294732-409caacc-a1c8-4eaf-8571-6952987b5135.jpg)

Please let me know if you need any other info.
(this happens both on mac & win, Firefox, last version)

**Comment by onemen** [comment]
I already have the fix for this issue in:  52b7538e

```css
#tabbrowser-tabs[multibar][orient=horizontal] .tabbrowser-tab[usercontextid] > .tab-stack > .tab-background > .tab-context-line {
  margin-top: -1px;
}
```

You can download this [xpi file](http://tabmixplus.org/dev-builds/test%20builds/1.0.0-pre.8.20220509.1.xpi) to test it
