### ISSUE TITLE
Rename Tab: Extra spaces squashed

### ISSUE THREAD

**Issue by VLM-TechEd** [onemen/TabMixPlus#192]
Win 10, Firefox current, TMP current (11/30)

This is the return of a problem from a prior release. When renaming a tab, if I type multiple space characters, only one is displayed in the tab. When I reopen the Tab Retitle dialog, the spaces are all present. Thank you.

**Comment by onemen** [comment]
Look at my answer from year ago #97

**Comment by VLM-TechEd** [comment]
Did this, not working this time around. I have Profile folder > chrome > userChrome.css containing exactly

 

.tabbrowser-tab .tab-label {

white-space: break-spaces; 

}

 

Created using Notepad. Restarted Firefox, no change.

**Comment by onemen** [comment]
By default, userChrome.css modifications are disabled in Firefox. You need to make sure that on the about:config page in Firefox, the `toolkit.legacyUserProfileCustomizations.stylesheets` preference is set to true and then restart the browser.

**Comment by VLM-TechEd** [comment]
Thank you. I always set that value to “True” whenever I install Firefox. I did check to be sure, of course.

**Comment by onemen** [comment]
Add important

```css
.tabbrowser-tab .tab-label {
  white-space: break-spaces !important;
}
```

**Comment by VLM-TechEd** [comment]
Thank you, the spaces now display correctly; Firefox is definitely reading userChrome.css. But now, very long tab titles  (e.g., Amazon products) wrap within the tabs, which was not the case before I added “!important;”. Interesting how interconnected these details can be.

**Comment by onemen** [comment]
this should work

```css
tabbrowser-tab .tab-label {
  white-space: -moz-pre-space !important;
}
```

**Comment by VLM-TechEd** [comment]
I added the period in front of tabbrowser-tab, and it works perfectly. Thank you!

**Comment by onemen** [comment]
you may have to change it to this:
```css
.tabbrowser-tab .tab-label {
  white-space: pre !important;
}
```
for Firefox 110
