### ISSUE TITLE
TMP pre.18:  Multiple spaces not displayed in tab titles

### ISSUE THREAD

**Issue by VLM-TechEd** [onemen/TabMixPlus#253]
As the headline says. This is a returning issue. Not a big one, unless one is visually impaired and trying to make things a bit more readable. :)

**Comment by onemen** [comment]
1. Add this to the file userChrome.css in your profile `chrome` folder

```css
.tabbrowser-tab .tab-label {
  white-space: pre !important;
}
```

2. In `about:config` set `toolkit.legacyUserProfileCustomizations.stylesheets` to `true`
