### ISSUE TITLE
Tab titles are sometimes truncated on the right

### ISSUE THREAD

**Issue by VLM-TechEd** [onemen/TabMixPlus#260]
Fx 122, Win 10.

This issue has been around for a long time, but I've never raised it because it seems rather minor. But sometimes, we do lose some useful information when tab titles are truncated on the right-hand side. It looks like a fade-out effect. And many tabs are not faded out at all. Weird.

This is not a problem of exceeding the maximum tab width we have set, which is 1280. These faded-out tabs are not even close to that width. 

I don't know what else to say, and frankly, if this never gets resolved, we will not suffer greatly. It's just a minor nuisance/annoyance, nothing more.

**Comment by onemen** [comment]
When tab title is longer then tab width Firefox fade-out the end.

**Comment by VLM-TechEd** [comment]
As I wrote in my original post, that is not the case.
![image](https://github.com/onemen/TabMixPlus/assets/8227398/5ad5f1b9-fe8a-4167-b234-42ffe4158cc1)
I hope I got the right image. If you look at the first tab, it fades out to the right. All the other tabs, some longer, look fine.

**Comment by VLM-TechEd** [comment]
Not completed. Please see the screen shot I sent.

**Comment by onemen** [comment]
![image](https://github.com/onemen/TabMixPlus/assets/3650909/35eff7c4-cb7f-4062-be8c-c19a624d8068)

Look, the same happening without Tab Mix.

This is the css rules from Firefox that set the  fade-out effect
```css
.tab-label-container[textoverflow][labeldirection=ltr]:not([pinned]),
.tab-label-container[textoverflow]:not([labeldirection], [pinned]):-moz-locale-dir(ltr) {
  direction: ltr;
  mask-image: linear-gradient(to left, transparent, black var(--tab-label-mask-size));
}

.tab-label-container[textoverflow][labeldirection=rtl]:not([pinned]),
.tab-label-container[textoverflow]:not([labeldirection], [pinned]):-moz-locale-dir(rtl) {
  direction: rtl;
  mask-image: linear-gradient(to right, transparent, black var(--tab-label-mask-size));
}
```

You can override it by adding this rules to your `userChrome.css`
```css
.tab-label-container[textoverflow][labeldirection]:not([pinned]),
.tab-label-container[textoverflow]:not([labeldirection], [pinned]) {
  mask-image: unset !important;
}

```
