### ISSUE TITLE
Themes break when there are too many rows

### ISSUE THREAD

**Issue by Merci-chao** [onemen/TabMixPlus#377]
The vertical background-size should match the maximum rows:
![圖片](https://github.com/user-attachments/assets/99df9b2c-f21d-4311-9a47-a3dcd8e8e240)

`:root /*fx115*/,
#navigator-toolbox {
	background-size: auto var(--multirows-background-size) !important;
}`

**Comment by onemen** [comment]
How to reproduce this issue?

Post info about:
theme name and version, Firefox version, operating system
also attach a file with your Tab mix preferences

**Comment by Merci-chao** [comment]
Just install a theme, say [Space stars](https://addons.mozilla.org/en-US/firefox/addon/space-stars), and have 7 or tab rows. The problem is more obvious on themes that don't repeat their background image.

**Comment by pyrates999** [comment]
This sounds like an issue with the theme then.

**Comment by onemen** [comment]
maybe it can be fixed with `background-repeat`

**Comment by Merci-chao** [comment]
> maybe it can be fixed with `background-repeat`

No, many themes are not designed to be repeatable, e.g. Autumns Light by MaDonna, Sunset in the Mountains by MaDonna, Spirited Away (Animated).

![Sunset in the Mountains by MaDonna](https://github.com/user-attachments/assets/119062c9-37df-41ed-84db-4b368af24f4d)

![Autumns Light by MaDonna](https://github.com/user-attachments/assets/d236297b-5546-46f2-bf72-9b4668e978cc)

![Spirited Away (Animated)](https://github.com/user-attachments/assets/162b3a08-d3bc-4d58-b972-04b3c5152ded)

**Comment by Merci-chao** [comment]
There are two solutions for that:
1. Observing the size of gNavToolbox and updating the vertical part of background-size as the height;
2. Set the height as the size of gNavToolbox with maximum rows.

Note that the height of auto-hide menubar and bookmarks toolbar (`browser.toolbars.bookmarks.visibility == "newtab"`) should also be counted, otherwise the image will bounce when the toolbars toggle, say when switching between a new-tab and a webpage, the bookmarks toolbar.

**Comment by onemen** [comment]
@Merci-chao,

try to add this rule to your profile `userChrome.css`

```css
#navigator-toolbox {
  background-repeat: repeat-y !important;
}
```

**Comment by onemen** [comment]
@Merci-chao,

try to add this rule to your profile `userChrome.css`

```css
#navigator-toolbox {
  background-size: cover;
}
```

or

```css
#navigator-toolbox {
  background-repeat: repeat-y !important;
}
```

**Comment by onemen** [comment]
I think i will add this to my code

```css
:root:is([lwtheme], [lwtheme-image]) #navigator-toolbox:has(#TabsToolbar[tabmix-multibar]) {
  background-size: cover;
}
```
