### ISSUE TITLE
When the sound icon is displayed, the locked/protected icons disappears

### ISSUE THREAD

**Issue by onemen** [onemen/TabMixPlus#93]
the Issue reported [here](http://tabmixplus.org/forum/viewtopic.php?f=4&t=20055&p=73831#p73831)

> I'm using 1.0.0-pre.3 on Firefox 94.
When the sound icon is displayed, the locked/protected icons disappears.
Is it possible to display an icons above the sound icon?

**Comment by 117649** [comment]
With proton the sound icon covers(hide) favicon entirely when displayed.

Didn't notice this since I use custom CSS to offset it and made favicon appear again.

CustomCSS theme like [Lepton](https://github.com/black7375/Firefox-UI-Fix) can just cancel this problem.

**Comment by onemen** [comment]
I can just add 
```css
opacity: 1 !important;
```

but i don't think it look good
![tab-icons](https://user-images.githubusercontent.com/3650909/140603316-732c6a0d-359d-4441-9094-a509cafc23df.png)

can you post the css you are using to offset the icons

**Comment by 117649** [comment]
> 
> 
> I can just add
> 
> ```css
> opacity: 1 !important;
> ```
> 
> but i don't think it look good ![tab-icons](https://user-images.githubusercontent.com/3650909/140603316-732c6a0d-359d-4441-9094-a509cafc23df.png)
> 
> can you post the css you are using to offset the icons

I'm using Lepton.

Honestly, it not pretty either.
![图片](https://user-images.githubusercontent.com/8281345/140603668-ccbc1294-8f55-4ada-9999-458ddda89f6e.png)

**Comment by onemen** [comment]
with this css rule we can offset our icons when the sound overly is visible
```css
.tab-icon-stack:is([soundplaying], [muted], [activemedia-blocked]) > .tab-protect-icon,
.tab-icon-stack:is([soundplaying], [muted], [activemedia-blocked]) > .tab-lock-icon,
.tab-icon-stack:is([soundplaying], [muted], [activemedia-blocked]) > .tab-reload-icon {
  opacity: 1 !important;
  margin-inline-start: 16px;
}
```
![tab-icons-offset](https://user-images.githubusercontent.com/3650909/140604176-2b7aa81d-e164-4cff-9b05-c610560433a7.png)

what do you think ?
